### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by tonychenc** [open-company/home#3]
模式有点像topcoder，又有些不太一样，没有竞争模式，一人一模块。

先抛出几个问题：
1. 项目的来源？作为公司总是要赚钱的吧？
2. 如何认定一个模块完成，是否有reviewer这个角色？或是结合TDD/BDD?
3. 模块的报酬不公开？自己报价？

**Comment by open-company** [comment]
是这样的，公共项目都是从核心项目中剥离出来的。
基本上都是涉及UI的开发，因为现在是起步阶段，人手有限。
而UI开发，只要统一了开发模式和工具，新手容易接手。

之所以采用Open Company这种形式，最根本原因还是为了节省管理成本。
有什么问题、想法都公开讨论，这样就形成了自组织，省略了管理层。
因为现阶段，所有人员都是开发人员。专门设一个管理层，不但奢侈，而且碍事。

如果新人想加入，想知道什么，尽管问，这样，问的人多了，后面的人看看就明白了。
再把FAQ整理一下，归入文档，可以省不少精力。

我们现在的工作模式是，和一直以来的工作模式没两样。按计划推进自己的开发进度。
如果有新人加入，则公开的项目可以分配出去。
如果暂时没有新人加入，我们也不无谓的耗费精力，去招人或是找人。

最后，回答你提出的几个问题：
1. 公司几年之内的重点是发展核心项目，不考虑赚钱。
2. 有reviewer这个角色，ocops童鞋就是干这个活的，同时还负责deploy。
    至于TDD/BDD这个根据个人喜好，和项目实际情况。由具体的开发人自主决定。
    毕竟，不管是T还是B，最终都是归结到D的。
    并且，作为UI项目，最终的裁判是UX。
3. 报酬自己愿意公开最好，其他人也可以有个参照，不愿意，可以不公开。
    如果你把这项工作看作是一次性的，也可以视为报价。
    我们的初衷是发展成员，所以希望能形成一套薪酬机制，最终实现为薪酬算法。
    当然，有可能作为初创公司，吸引力不够。
    大家只想临时兼点职，赚点外快，这也完全可以理解。而且也是很欢迎的。

作为初创公司，我们的想法其实很简单。
尽量节省管理成本和运营成本，尽快推动项目的整体进度。

**Comment by tonychenc** [comment]
1. 这种模式首先带来的问题是开发过程中和完成之后的维护人员变动，这个问题所带来的风险如何把控？

2. 薪酬计算一般按估算的工作量来决定，但每个人工作效率，估算的工作量及预期的时薪的差异会导致最终的结果的不同。这是个挺主观也挺经验的估算，建立一套估算标准是可以的，但基于代码量，实现一个薪酬标准算法不太准确。这个薪酬最终是由谁来定呢？

**Comment by open-company** [comment]
1. 首先，UI技术不是rock science，而是日新月异，飞速变化的时髦玩意。其次，每一个OCOSP都是最小化到一个开发人员半天、一天就可以完成的，目前还看不出有什么重大的维护需求。
2. 这里没有一个标准的salary algorithm，而是有一个salary algorithm collection。每个人都可以提交任意的多个salary algorithm。开发人员可以选择自己适合的salary algorithm。
